project_name: securityhub-exporter
builds:
  - main: .
    ldflags:
      - -s -w
      - -X github.com/kota65535/securityhub-exporter/cmd.version={{.Version}}
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: securityhub-exporter
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
