name: Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Get tool versions
        uses: kota65535/github-asdf-parse-action@v1
        id: versions
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.versions.outputs.golang }}
      - name: Run test
        run: make clean test
